# Generated by Django 5.0.3 on 2024-03-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Medicines',
        ),
    ]
